name: dev-check
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: make install
      - name: Test
        run: make test
      - name: Lint
        run: make lint
  coverage:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: a288ee7cc50b292f248c5f6afb5270985c1a103d72609c4028240588863885ae
        with:
          coverageCommand: make test